# Generated by Django 2.2.3 on 2019-07-29 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('mobile', models.CharField(max_length=11, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('user_type', models.CharField(choices=[('SU', 'Super User'), ('CL', 'Client'), ('RES', 'Responder'), ('AD', 'Admin'), ('SA', 'Sub-Admin')], max_length=2)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Responder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100, null=True)),
                ('serial_num', models.CharField(max_length=3, unique=True)),
                ('responder_code', models.CharField(max_length=9, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], max_length=10)),
                ('profile_pic', models.ImageField(null=True, upload_to='responders_pics')),
                ('areas_of_concentration', models.ManyToManyField(null=True, to='core.AreaOfConcentration')),
                ('gender', models.ForeignKey(on_delete='on_delete', to='core.Gender')),
                ('kits', models.ManyToManyField(null=True, to='core.Kit')),
                ('local_govt', models.ForeignKey(on_delete='on_delete', to='core.LocalGovernment')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Member')),
                ('state', models.ForeignKey(on_delete='on_delete', to='core.State')),
            ],
            options={
                'ordering': ['responder_code'],
            },
        ),
    ]
